### ISSUE TITLE
[APP] Improve response time of the first question

### ISSUE THREAD

**Issue by gs-Manuel** [Arquisoft/wiq_es1c#127]
Think about it.

**Comment by RubenFern** [comment]
To optimize the display of the first question I modified the Game microservice to return the questions from a database in MongoDB, instead of requesting in real time the question from WikiData.

The database in MongoDB contains 1000 questions that are refreshed daily by deleting the 100 oldest questions and adding another 100 questions.

**Comment by Manueluz** [comment]
@RubenFern Add this cache architecture to an ADR please!

**Comment by RubenFern** [comment]
> @RubenFern Add this cache architecture to an ADR please!

Done!!
